/*
 * JLibs: Common Utilities for Java
 * Copyright (C) 2009  Santhosh Kumar T
 * <p/>
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * <p/>
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 */

package jlibs.core.annotation.processing;

import jlibs.core.lang.model.ModelUtil;

import javax.lang.model.element.TypeElement;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;

/**
 * @author Santhosh Kumar T
 */
public class Printer{
    public TypeElement clazz;
    public String generatedQName;
    public String generatedPakage;
    public String generatedClazz;

    public int indent;
    PrintWriter ps;

    public Printer(PrintWriter ps){
        this.ps = ps;
    }

    private boolean doIndent = true;
    private void indent(){
        if(doIndent){
            if(emptyLine){
                println();
                emptyLine = false;
            }
            for(int i=0; i<indent; i++)
                ps.print("    ");
        }
    }
    public void println(String str){
        indent();
        ps.println(str);
        doIndent = true;
    }

    public void print(String str){
        indent();
        ps.print(str);
        doIndent = false;
    }

    private boolean emptyLine;
    public void emptyLine(boolean reqd){
        emptyLine = reqd;
    }

    public void println(){
        ps.println();
        doIndent = true;
    }

    public void close(){
        ps.close();
    }
    
    private static Map<TypeElement, Printer> registry = new HashMap<TypeElement, Printer>();
    public static Printer get(TypeElement clazz, String format) throws IOException{
        Printer printer = registry.get(clazz);
        if(printer==null){
            String str[] = ModelUtil.findClass(clazz, format);
            PrintWriter writer = new PrintWriter(Environment.get().getFiler().createSourceFile(str[0]).openWriter());
            printer=new Printer(writer);
            printer.clazz = clazz;
            printer.generatedQName = str[0];
            printer.generatedPakage = str[1];
            printer.generatedClazz = str[2];
            registry.put(clazz, printer);
        }
        return printer;
    }

    /*-------------------------------------------------[ Helpers ]---------------------------------------------------*/

    public void printPackage(){
        if(generatedPakage !=null && generatedPakage.length()>0){
            println("package "+generatedPakage +";");
            emptyLine(true);
        }
    }

    public void printClassDoc(){
        println("/**");
        println(" * DON'T EDIT THIS FILE. THIS IS GENERATED BY JLIBS");
        println(" *");
        println(" * @author Santhosh Kumar T");
        println(" */");
    }
}
